# Basic
title: allen.wu
subtitle: 个人网站
description: 一只思考的猿.喜欢研究开源的RPC/MQ.
# 头像里面的标题
avatarTitle: allen.wu
# 头像里面的描述
avatarDesc: Java / Go / 分布式
url: "http://baixin.io"

# Comment
comment:
    disqus: allen.wu

# Social
social:
    weibo: 2682299033
    github: allenfancy
    # twitter: 
    mail: allenfancy520@gmail.com

baidu:
    id: 452d12928a8b77b1287fb6c4cc2eb286  

ga:
    id: UA-119193482-1
    host: auto  



permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 关于我, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"



theme: jekyll-theme-minimal